version: 2.1
orbs:
  env: christeredvartsen/persist-env@0.1.0
jobs:
  build:
    machine: true
    steps:
      - run: echo 'deko' > temp.txt
      - env/set-env-var:
          var-name: DEJAN
          var-value: ${cat temp.txt}
      - env/persist-env
      - run: echo "Variable value of DEJAN is $DEJAN"
