version: 2.1
orbs:
  env: christeredvartsen/persist-env@0.1.0
jobs:
  build:
    machine: true
    steps:
      - run: echo 'deko' > temp.txt
      - env/set-env-var:
          var-name: DEJAN
          var-value: $(cat temp.txt)
      - run: rm temp.txt
      - env/persist-env
      - run: echo "Variable value of DEJAN is $DEJAN"
      - run: echo "Same variable in another step of the same job $DEJAN"
  deploy:
    machine: true
    steps:
      - env/attach-env
      - run: echo "Variable in the other job $DEJAN"
 workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
