version: 2.1
orbs:
  env: christeredvartsen/persist-env@0.1.0
jobs:
  build:
    machine: true
    steps:
      - env/set-env-var:
          var-name: DEJAN
          var-value: deko
      - env/persist-env
      - run: echo "Env variable from previous step is $DEJAN"
      - run: DEJAN='second'
      - env/set-env-var:
          var-name: DEJAN
      - env/persist-env
      - run: echo "Env variable from previous step is $DEJAN"
